---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  empty-lines:
    max: 2
  trailing-spaces: enable

ignore: |
  .git/
  elastic/
  splunk/
  microsoft-sentinel/
  wazuh/
  carbonblack/
