title: Kubernetes Service Account Token Exfiltration
id: 7e706879-53f8-4d5d-b707-297e90de805c
status: experimental
description: |
  Detects reads of service account token secrets.
author: Security Team
date: 2026/08/01
references:
  - https://attack.mitre.org/techniques/T1528/
logsource:
  product: kubernetes
  service: audit
detection:
  selection:
    verb|contains:
      - 'get'
      - 'list'
    objectRef.resource: 'secrets'
    objectRef.name|contains: 'token'
  condition: selection
fields:
  - user.username
  - sourceIPs
  - objectRef.namespace
  - objectRef.name
falsepositives:
  - Authorized administrative activity matching this behavior.
level: high
tags:
  - attack.t1528
  - attack.credential-access
