title: Kubernetes Admission Webhook Tampering
id: 3b72e8d8-b3bd-4d7b-9295-2c78e5978cf3
status: experimental
description: |
  Detects changes to validating or mutating admission webhooks.
author: Security Team
date: 2026/08/01
references:
  - https://attack.mitre.org/techniques/T1562/
logsource:
  product: kubernetes
  service: audit
detection:
  selection:
    verb|contains:
      - 'create'
      - 'update'
      - 'patch'
      - 'delete'
    objectRef.resource|contains:
      - 'validatingwebhookconfigurations'
      - 'mutatingwebhookconfigurations'
  condition: selection
fields:
  - user.username
  - sourceIPs
  - objectRef.namespace
  - objectRef.name
falsepositives:
  - Authorized administrative activity matching this behavior.
level: high
tags:
  - attack.t1562.001
  - attack.defense_evasion
