// Title: Unsecured Credentials
// Description: Detects indicators of Unsecured Credentials (T1552)
// MITRE ATT&CK: T1552
// Severity: medium
// Tactic: credential-access
// Author: Wahid Hendrawan
// Date: 2026-06-04
// References:
//   - https://attack.mitre.org/techniques/T1552/

DeviceProcessEvents
| where Timestamp > ago(24h)
| where findstr /si password OR dir *password*
| project Timestamp, DeviceName, AccountName, FileName, ProcessCommandLine,
          InitiatingProcessFileName, InitiatingProcessCommandLine
| order by Timestamp desc
