// Title: Impair Defenses
// Description: Detects indicators of Impair Defenses (T1562)
// MITRE ATT&CK: T1562
// Severity: medium
// Tactic: defense-evasion
// Author: Wahid Hendrawan
// Date: 2026-06-04
// References:
//   - https://attack.mitre.org/techniques/T1562/

DeviceProcessEvents
| where Timestamp > ago(24h)
| where disable defender or AV
| project Timestamp, DeviceName, AccountName, FileName, ProcessCommandLine,
          InitiatingProcessFileName, InitiatingProcessCommandLine
| order by Timestamp desc
