"""Generate COVERAGE.md and coverage.json (ATT&CK Navigator)."""

from __future__ import annotations

import json
import sys
from argparse import ArgumentParser, Namespace
from collections import defaultdict
from pathlib import Path

from ..parsers import parse
from ..paths import ROOT, iter_rules


def add_arguments(parser: ArgumentParser) -> None:
    parser.add_argument("--out-md", default=str(ROOT / "COVERAGE.md"))
    parser.add_argument("--out-json", default=str(ROOT / "coverage.json"))


def _build() -> tuple[
    dict[str, set[str]],
    dict[str, dict[str, set[str]]],
    dict[str, list[Path]],
]:
    """Return (technique_to_platforms, platform_to_techniques, rules)."""
    rules = iter_rules()
    t2p: dict[str, set[str]] = defaultdict(set)
    p2t: dict[str, dict[str, set[str]]] = defaultdict(lambda: defaultdict(set))
    for platform, files in rules.items():
        for f in files:
            techs = parse(platform, f)["techniques"]
            for t in techs:
                t2p[t].add(platform)
                p2t[platform][t].add(str(f.relative_to(ROOT)))
    return t2p, p2t, rules


def _markdown(t2p, p2t, rules) -> str:
    out: list[str] = []
    out.append("# MITRE ATT&CK Coverage\n")
    out.append("> Auto-generated by `python -m detection_rules coverage`. **Do not edit manually.**\n")
    out.append("")
    out.append("## Ringkasan\n")
    out.append(f"- Total file rule         : **{sum(len(v) for v in rules.values())}**")
    out.append(f"- Total teknik unik       : **{len(t2p)}**")
    out.append("")
    out.append("### Per Platform\n")
    out.append("| Platform | Rule | Teknik unik |")
    out.append("|---|---:|---:|")
    for p in ("sigma", "elastic", "splunk", "microsoft-sentinel", "wazuh", "carbonblack"):
        out.append(f"| {p} | {len(rules.get(p, []))} | {len(p2t.get(p, {}))} |")
    out.append("")
    out.append("## Coverage Matrix\n")
    out.append("Tanda ✅ = ada minimal satu rule pada platform tersebut yang memetakan teknik.\n")
    out.append("| Technique | Sigma | Elastic | Splunk | Sentinel | Wazuh | CarbonBlack |")
    out.append("|---|:---:|:---:|:---:|:---:|:---:|:---:|")

    def mark(p: str, t: str) -> str:
        return "✅" if p in t2p.get(t, set()) else "·"

    for tech in sorted(t2p):
        out.append(
            f"| `{tech}` | {mark('sigma', tech)} | {mark('elastic', tech)} | "
            f"{mark('splunk', tech)} | {mark('microsoft-sentinel', tech)} | "
            f"{mark('wazuh', tech)} | {mark('carbonblack', tech)} |"
        )

    out.append("")
    out.append("## Detail per Platform\n")
    for platform, techmap in p2t.items():
        if not techmap:
            continue
        out.append(f"### {platform}\n")
        out.append("| Technique | Rule files |")
        out.append("|---|---|")
        for tech in sorted(techmap):
            files = sorted(techmap[tech])
            preview = ', '.join('`' + f + '`' for f in files[:5])
            ellipsis = ' ...' if len(files) > 5 else ''
            out.append(f"| `{tech}` | {preview}{ellipsis} |")
        out.append("")
    return "\n".join(out) + "\n"


def _navigator(t2p) -> dict:
    techniques = []
    for tech, platforms in sorted(t2p.items()):
        techniques.append({
            "techniqueID": tech,
            "score": len(platforms),
            "comment": f"Covered by: {', '.join(sorted(platforms))}",
            "enabled": True,
        })
    return {
        "name": "Detection-Rules Coverage",
        "versions": {"layer": "4.5", "navigator": "5.0", "attack": "16"},
        "domain": "enterprise-attack",
        "description": "MITRE ATT&CK coverage auto-generated from wahidhendrawan/Detection-Rules",
        "filters": {"platforms": ["Linux", "Windows", "macOS", "Network", "Cloud"]},
        "sorting": 3,
        "layout": {"layout": "side", "showName": True, "showID": False},
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffe6e6", "#ff6666", "#990000"],
            "minValue": 1,
            "maxValue": 6,
        },
        "showTacticRowBackground": False,
        "selectTechniquesAcrossTactics": True,
    }


def run(args: Namespace) -> int:
    t2p, p2t, rules = _build()
    Path(args.out_md).write_text(_markdown(t2p, p2t, rules))
    Path(args.out_json).write_text(json.dumps(_navigator(t2p), indent=2) + "\n")
    print(f"[+] Wrote {args.out_md}")
    print(f"[+] Wrote {args.out_json} ({len(t2p)} techniques)")
    return 0
