"""Tag rules with MITRE ATT&CK threat actor / campaign references."""

from __future__ import annotations

import json
from argparse import ArgumentParser, Namespace
from pathlib import Path

from ..parsers import parse
from ..paths import ROOT, iter_rules

# Subset of MITRE ATT&CK Groups (G-IDs) and which techniques they use,
# focused on the top tracked threat actors. Source: attack.mitre.org/groups/
# Auto-generated, then trimmed to the techniques present in this repo.
GROUP_TO_TECHNIQUES: dict[str, dict] = {
    "G0007": {
        "name": "APT28 (Fancy Bear)",
        "techniques": ["T1003.001", "T1059.001", "T1098", "T1133", "T1110",
                       "T1190", "T1566.001", "T1059.003", "T1547.001",
                       "T1078", "T1218.011"],
    },
    "G0016": {
        "name": "APT29 (Cozy Bear)",
        "techniques": ["T1003.001", "T1059.001", "T1078.004", "T1098.001",
                       "T1133", "T1546", "T1566.001", "T1218.011",
                       "T1547.001", "T1027"],
    },
    "G0032": {
        "name": "Lazarus Group",
        "techniques": ["T1059.001", "T1059.003", "T1003", "T1027",
                       "T1486", "T1490", "T1218.005", "T1547.001",
                       "T1543.003", "T1053.005"],
    },
    "G0050": {
        "name": "APT32 (OceanLotus)",
        "techniques": ["T1059.001", "T1059.003", "T1218.005", "T1218.010",
                       "T1547.001", "T1003.001", "T1027"],
    },
    "G0096": {
        "name": "APT41",
        "techniques": ["T1059.001", "T1003.001", "T1190", "T1133",
                       "T1505.003", "T1543.003", "T1574.002", "T1078"],
    },
    "G0102": {
        "name": "Wizard Spider (Conti / TrickBot affiliate)",
        "techniques": ["T1486", "T1490", "T1003.001", "T1059.001",
                       "T1547.001", "T1543.003", "T1053.005", "T1078",
                       "T1218.011", "T1110"],
    },
    "G0008": {
        "name": "Carbanak / FIN7",
        "techniques": ["T1059.001", "T1059.003", "T1218.005", "T1547.001",
                       "T1543.003", "T1003", "T1110"],
    },
    "G0046": {
        "name": "FIN7",
        "techniques": ["T1059.001", "T1059.005", "T1218.005", "T1547.001",
                       "T1543.003", "T1003.001"],
    },
    "G1015": {
        "name": "Scattered Spider (UNC3944)",
        "techniques": ["T1078.004", "T1098.001", "T1133", "T1110",
                       "T1486", "T1059.001", "T1003.001", "T1556.006"],
    },
    "G0102_BLACKCAT": {
        "name": "ALPHV / BlackCat",
        "techniques": ["T1486", "T1490", "T1003.001", "T1059.001",
                       "T1543.003", "T1547.001", "T1078", "T1190"],
    },
    "G0102_LOCKBIT": {
        "name": "LockBit",
        "techniques": ["T1486", "T1490", "T1003.001", "T1059.001",
                       "T1547.001", "T1543.003", "T1133", "T1078"],
    },
}


def add_arguments(parser: ArgumentParser) -> None:
    parser.add_argument("--out-md", default=str(ROOT / "docs/threat-actors.md"))
    parser.add_argument("--out-json", default=str(ROOT / "docs/threat-actors.json"))


def run(args: Namespace) -> int:
    # technique -> [(group_id, group_name)]
    tech_to_groups: dict[str, list[tuple[str, str]]] = {}
    for gid, info in GROUP_TO_TECHNIQUES.items():
        for t in info["techniques"]:
            tech_to_groups.setdefault(t, []).append((gid, info["name"]))

    # rule_file -> {techs, groups}
    by_rule: dict[str, dict] = {}
    by_group: dict[str, list[dict]] = {}

    for platform, files in iter_rules().items():
        for f in files:
            techs = parse(platform, f)["techniques"]
            if not techs:
                continue
            groups: set[tuple[str, str]] = set()
            for t in techs:
                for g in tech_to_groups.get(t, []):
                    groups.add(g)
            if not groups:
                continue
            rel = str(f.relative_to(ROOT))
            entry = {
                "platform": platform,
                "techniques": sorted(techs),
                "groups": [{"id": gid, "name": name} for gid, name in sorted(groups)],
            }
            by_rule[rel] = entry
            for gid, name in groups:
                by_group.setdefault(name, []).append({"file": rel, "platform": platform})

    payload = {
        "summary": {
            "rules_with_actor_mapping": len(by_rule),
            "actors_referenced": len(by_group),
        },
        "by_rule": by_rule,
        "by_group": by_group,
    }
    Path(args.out_json).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out_json).write_text(json.dumps(payload, indent=2) + "\n")

    lines: list[str] = []
    lines.append("# Threat Actor Mapping\n")
    lines.append("> Auto-generated by `python -m detection_rules cti`. **Do not edit manually.**\n")
    lines.append("")
    lines.append("This document links repository rules to known MITRE ATT&CK Groups based")
    lines.append("on the techniques they detect. Use it to identify which rules likely")
    lines.append("trigger when a specific threat actor's TTPs are observed in your environment.\n")
    lines.append("")
    lines.append(f"- Rules with actor mapping : **{payload['summary']['rules_with_actor_mapping']}**")
    lines.append(f"- Actors referenced        : **{payload['summary']['actors_referenced']}**")
    lines.append("")
    lines.append("## Rules grouped by threat actor\n")
    for actor in sorted(by_group):
        lines.append(f"### {actor}\n")
        for entry in sorted(by_group[actor], key=lambda e: e["file"]):
            lines.append(f"- `{entry['file']}` *({entry['platform']})*")
        lines.append("")

    Path(args.out_md).write_text("\n".join(lines) + "\n")
    print(f"[+] Wrote {args.out_md}")
    print(f"[+] Wrote {args.out_json}")
    print(f"    {payload['summary']['rules_with_actor_mapping']} rules → "
          f"{payload['summary']['actors_referenced']} actors")
    return 0
