"""Report top ATT&CK techniques NOT yet covered."""

from __future__ import annotations

from argparse import ArgumentParser, Namespace
from pathlib import Path

from ..parsers import parse
from ..paths import ROOT, iter_rules

# "Top" techniques to prioritize, derived from public threat reports
# (Red Canary Threat Detection Report 2024, MITRE Top Techniques 2023,
# Mandiant M-Trends 2024, CISA #StopRansomware joint advisories).
# Update when new threat reports are published.
PRIORITY_TECHNIQUES: list[tuple[str, str, str]] = [
    # (technique_id, name, source)
    ("T1059",     "Command and Scripting Interpreter",        "Red Canary 2024 #1"),
    ("T1059.001", "PowerShell",                                "Red Canary 2024 #2"),
    ("T1059.003", "Windows Command Shell",                     "Red Canary 2024 #3"),
    ("T1027",     "Obfuscated Files or Information",           "Red Canary 2024"),
    ("T1218",     "System Binary Proxy Execution",             "Red Canary 2024"),
    ("T1218.011", "Rundll32",                                  "Red Canary 2024 top-10"),
    ("T1218.005", "Mshta",                                     "Red Canary 2024 top-10"),
    ("T1547.001", "Registry Run Keys / Startup Folder",        "MITRE Top Techniques 2023"),
    ("T1543.003", "Windows Service",                           "MITRE Top Techniques 2023"),
    ("T1053.005", "Scheduled Task",                            "MITRE Top Techniques 2023"),
    ("T1003",     "OS Credential Dumping",                     "M-Trends 2024"),
    ("T1003.001", "LSASS Memory",                              "M-Trends 2024"),
    ("T1486",     "Data Encrypted for Impact (Ransomware)",    "CISA Joint Advisory"),
    ("T1490",     "Inhibit System Recovery",                   "CISA Joint Advisory"),
    ("T1078",     "Valid Accounts",                            "M-Trends 2024"),
    ("T1078.004", "Cloud Accounts",                            "M-Trends 2024"),
    ("T1190",     "Exploit Public-Facing Application",         "M-Trends 2024 entry-vector"),
    ("T1133",     "External Remote Services",                  "M-Trends 2024 entry-vector"),
    ("T1505.003", "Web Shell",                                 "M-Trends 2024"),
    ("T1566.001", "Phishing: Spearphishing Attachment",        "M-Trends 2024 entry-vector"),
    ("T1566.002", "Phishing: Spearphishing Link",              "M-Trends 2024 entry-vector"),
    ("T1056.001", "Keylogging",                                "Red Canary"),
    ("T1572",     "Protocol Tunneling",                        "Red Canary"),
    ("T1071.004", "DNS",                                       "Red Canary"),
    ("T1574.002", "DLL Side-Loading",                          "M-Trends 2024"),
    ("T1098",     "Account Manipulation",                      "M-Trends 2024"),
    ("T1136.001", "Local Account Creation",                    "Common"),
    ("T1110",     "Brute Force",                               "Common"),
    ("T1110.001", "Password Guessing",                         "Common"),
    ("T1611",     "Escape to Host (Container Escape)",         "Cloud-native threats"),
]


def add_arguments(parser: ArgumentParser) -> None:
    parser.add_argument("--out-md", default=str(ROOT / "docs/gap-analysis.md"))


def _covered_techniques() -> set[str]:
    covered: set[str] = set()
    for platform, files in iter_rules().items():
        for f in files:
            covered.update(parse(platform, f)["techniques"])
    return covered


def run(args: Namespace) -> int:
    covered = _covered_techniques()
    missing = [
        (t, name, src) for (t, name, src) in PRIORITY_TECHNIQUES
        if t not in covered
    ]
    present = [
        (t, name, src) for (t, name, src) in PRIORITY_TECHNIQUES
        if t in covered
    ]

    lines: list[str] = []
    lines.append("# Gap Analysis — Top Priority Techniques\n")
    lines.append("> Auto-generated by `python -m detection_rules gap`. **Do not edit manually.**\n")
    lines.append("")
    lines.append("This report compares the repository's coverage against techniques")
    lines.append("frequently observed in public threat reports (Red Canary, MITRE,")
    lines.append("Mandiant M-Trends, CISA Joint Advisories).\n")
    lines.append("")
    lines.append(f"## Summary")
    lines.append("")
    lines.append(f"- Priority techniques tracked : **{len(PRIORITY_TECHNIQUES)}**")
    lines.append(f"- Covered                     : **{len(present)}**")
    lines.append(f"- Missing                     : **{len(missing)}**")
    lines.append(
        f"- Coverage of priority list   : **{round(100*len(present)/len(PRIORITY_TECHNIQUES), 1)}%**"
    )
    lines.append("")

    lines.append(f"## ❌ Missing ({len(missing)})\n")
    if not missing:
        lines.append("All priority techniques are covered. 🎉\n")
    else:
        lines.append("| Technique | Name | Source |")
        lines.append("|---|---|---|")
        for t, name, src in missing:
            lines.append(f"| `{t}` | {name} | {src} |")
        lines.append("")

    lines.append(f"## ✅ Covered ({len(present)})\n")
    lines.append("| Technique | Name | Source |")
    lines.append("|---|---|---|")
    for t, name, src in present:
        lines.append(f"| `{t}` | {name} | {src} |")
    lines.append("")

    Path(args.out_md).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out_md).write_text("\n".join(lines) + "\n")
    print(f"[+] Wrote {args.out_md}")
    print(f"    Missing {len(missing)}/{len(PRIORITY_TECHNIQUES)} priority techniques")
    return 0
