"""Compute Detection-as-Code quality metrics per rule."""

from __future__ import annotations

import json
import sys
from argparse import ArgumentParser, Namespace
from pathlib import Path

from ..parsers import parse
from ..paths import ROOT, iter_rules

SEVERITY_WEIGHT = {
    "critical": 5, "high": 4, "medium": 3, "low": 2, "informational": 1,
    "info": 1, None: 0, "": 0,
}

# rough FP-risk per (logsource keyword, binary keyword) — higher = more noise
HIGH_FP_KEYWORDS = (
    "powershell", "cmd", "wmic", "rundll32", "regsvr32", "schtasks",
    "process_creation",
)


def _fp_risk(rule: dict, path: Path) -> int:
    blob = (path.name + " " + " ".join(str(rule.get("title") or ""))).lower()
    return sum(1 for kw in HIGH_FP_KEYWORDS if kw in blob)


def _score(rule: dict, path: Path) -> dict:
    techs = rule["techniques"]
    sev = str(rule.get("level") or "").lower()
    sev_score = SEVERITY_WEIGHT.get(sev, 0)
    technique_score = min(len(techs), 5)  # capped
    fp_risk = _fp_risk(rule, path)

    # 0-100 quality score
    quality = (
        20 * (1 if techs else 0)        # has ATT&CK mapping
        + 15 * (1 if sev_score else 0)  # has severity
        + 15 * (1 if rule.get("title") and rule["title"] != path.stem else 0)
        + 20 * (sev_score / 5)
        + 20 * (technique_score / 5)
        + 10 * (1 - min(fp_risk, 5) / 5)
    )
    return {
        "title": rule.get("title") or path.stem,
        "severity": sev or None,
        "techniques": sorted(techs),
        "fp_risk": fp_risk,
        "quality_score": round(quality, 1),
    }


def add_arguments(parser: ArgumentParser) -> None:
    parser.add_argument("--out-json", default=str(ROOT / "metrics.json"))
    parser.add_argument("--out-md", default=str(ROOT / "docs/metrics.md"))


def run(args: Namespace) -> int:
    rules = iter_rules()
    per_rule: list[dict] = []
    per_platform: dict[str, list[float]] = {p: [] for p in rules}

    for platform, files in rules.items():
        for f in files:
            try:
                rule = parse(platform, f)
            except Exception as e:
                print(f"[warn] failed to parse {f}: {e}", file=sys.stderr)
                continue
            entry = _score(rule, f)
            entry["platform"] = platform
            entry["file"] = str(f.relative_to(ROOT))
            per_rule.append(entry)
            per_platform[platform].append(entry["quality_score"])

    summary = {
        "total_rules": len(per_rule),
        "average_quality": round(
            sum(r["quality_score"] for r in per_rule) / max(len(per_rule), 1), 1
        ),
        "rules_with_attack_mapping": sum(1 for r in per_rule if r["techniques"]),
        "rules_without_attack_mapping": sum(1 for r in per_rule if not r["techniques"]),
        "high_fp_risk": sum(1 for r in per_rule if r["fp_risk"] >= 3),
        "per_platform": {
            p: {
                "count": len(scores),
                "avg_quality": round(sum(scores) / max(len(scores), 1), 1),
            }
            for p, scores in per_platform.items()
        },
    }

    payload = {"summary": summary, "rules": per_rule}
    Path(args.out_json).write_text(json.dumps(payload, indent=2) + "\n")

    # markdown report — bottom-10 + per-platform stats
    bottom = sorted(per_rule, key=lambda r: r["quality_score"])[:10]
    lines: list[str] = []
    lines.append("# Detection-as-Code Quality Metrics\n")
    lines.append("> Auto-generated by `python -m detection_rules metrics`. **Do not edit manually.**\n\n")
    lines.append("## Summary\n")
    lines.append(f"- Total rules                : **{summary['total_rules']}**")
    lines.append(f"- Average quality score      : **{summary['average_quality']}/100**")
    lines.append(f"- Rules with ATT&CK mapping  : **{summary['rules_with_attack_mapping']}**")
    lines.append(f"- Rules WITHOUT ATT&CK       : **{summary['rules_without_attack_mapping']}**")
    lines.append(f"- High FP-risk (score ≥ 3)   : **{summary['high_fp_risk']}**")
    lines.append("")
    lines.append("## Per Platform\n")
    lines.append("| Platform | Rules | Avg quality |")
    lines.append("|---|---:|---:|")
    for p, s in summary["per_platform"].items():
        lines.append(f"| {p} | {s['count']} | {s['avg_quality']} |")
    lines.append("")
    lines.append("## Bottom-10 Rules (lowest quality, prioritize for review)\n")
    lines.append("| Score | Platform | File | Issues |")
    lines.append("|---:|---|---|---|")
    for r in bottom:
        issues = []
        if not r["techniques"]:
            issues.append("no ATT&CK mapping")
        if not r["severity"]:
            issues.append("no severity")
        if r["fp_risk"] >= 3:
            issues.append(f"high FP risk ({r['fp_risk']})")
        lines.append(
            f"| {r['quality_score']} | {r['platform']} | "
            f"`{r['file']}` | {', '.join(issues) or '—'} |"
        )
    lines.append("")
    Path(args.out_md).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out_md).write_text("\n".join(lines) + "\n")

    print(f"[+] Wrote {args.out_json}")
    print(f"[+] Wrote {args.out_md}")
    print(f"    Average quality: {summary['average_quality']}/100 across {summary['total_rules']} rules")
    return 0
