title: Credentials in Files - Config File Access
id: 8ef19d8a-ae40-440a-aa1c-7f5866945a55
status: experimental
description: |
  Detects indicators of Credentials in Files - Config File Access (T1552.001).
author: Wahid Hendrawan
date: 2026/06/04
references:
  - https://attack.mitre.org/techniques/T1552/001/
logsource:
  product: windows
  category: file_access
detection:
  selection:
    TargetFilename|endswith:
      - 'web.config'
      - 'appsettings.json'
      - '.env'
      - 'wp-config.php'
      - 'credentials.xml'
  filter_apps:
    Image|endswith:
      - '\\w3wp.exe'
      - '\\dotnet.exe'
      - '\\node.exe'
  condition: selection and not filter_apps
fields:
  - Image
  - CommandLine
  - User
falsepositives:
  - Developers editing config files.
  - Deployment tools.
level: medium
tags:
  - attack.t1552.001
  - attack.credential-access
